#!/usr/bin/env python3
"""
Output Archive Manager

Snapshots generated outputs before regeneration so old versions are
preserved but clearly separated from current content.

(c) RSP Management Solutions LLC.
No assumption of ownership of client intellectual property.

Usage:
    # Snapshot all current outputs into archive/
    python3 scripts/archive.py snapshot

    # Snapshot with a label (e.g., before a major regeneration)
    python3 scripts/archive.py snapshot --label "pre-phase2-replan"

    # Archive a single file before overwriting it
    python3 scripts/archive.py file docs/BUSINESS_CASE.md

    # List all archived snapshots
    python3 scripts/archive.py list

    # Show what changed between two snapshots
    python3 scripts/archive.py diff 2026-02-11T21-30-00 2026-02-12T09-15-00

    # Restore a file from an archive (copies to current, does NOT delete archive)
    python3 scripts/archive.py restore 2026-02-11T21-30-00 docs/BUSINESS_CASE.md
"""

import argparse
import hashlib
import json
import os
import shutil
import sys
from datetime import datetime
from pathlib import Path

# Project root is one level above scripts/
PROJECT_ROOT = Path(__file__).resolve().parent.parent
ARCHIVE_DIR = PROJECT_ROOT / "archive"

# Files and directories that contain regenerable outputs.
# Paths are relative to PROJECT_ROOT.
OUTPUT_PATHS = [
    # Generated docs
    "docs/BUSINESS_CASE.md",
    "docs/POST_LAUNCH_EVALUATION.md",
    "docs/JIRA_IMPORT.csv",
    "docs/JIRA_IMPORT.md",
    "docs/ROADMAP.md",
    "docs/CRITICAL_PATH_ANALYSIS.md",
    # Analysis artifacts (produced by Claude Code sessions)
    "analysis/PROJECT_STRUCTURE.md",
    "analysis/MODULE_CLASSIFICATIONS.md",
    "analysis/WCAG_AUDIT.md",
    "analysis/ARCHITECTURE_AUDIT.md",
    "analysis/ANALYSIS_LOG.md",
    # Figma prompts (entire directory — regenerated by generate_figma_prompts.py)
    "figma_prompts/",
    # Stories (entire directory — authored over time, worth snapshotting)
    "stories/",
]


def file_hash(path: Path) -> str:
    """SHA-256 of a file's contents."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()[:12]


def timestamp_label() -> str:
    """ISO-ish timestamp safe for directory names."""
    return datetime.now().strftime("%Y-%m-%dT%H-%M-%S")


def collect_files() -> list[Path]:
    """Resolve OUTPUT_PATHS to a flat list of existing files."""
    files = []
    for entry in OUTPUT_PATHS:
        p = PROJECT_ROOT / entry
        if p.is_file():
            files.append(p)
        elif p.is_dir():
            for child in sorted(p.rglob("*")):
                if child.is_file() and not child.name.startswith("."):
                    files.append(child)
    return files


def do_snapshot(label: str | None = None) -> Path:
    """Archive all current outputs into a timestamped directory."""
    ts = timestamp_label()
    snap_name = ts if not label else ts + "_" + label.replace(" ", "-")
    snap_dir = ARCHIVE_DIR / snap_name
    snap_dir.mkdir(parents=True, exist_ok=True)

    files = collect_files()
    if not files:
        print("No output files found to archive.")
        sys.exit(0)

    manifest = {
        "snapshot": snap_name,
        "created": datetime.now().isoformat(),
        "label": label or "",
        "files": [],
    }

    copied = 0
    for src in files:
        rel = src.relative_to(PROJECT_ROOT)
        dest = snap_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dest)
        manifest["files"].append({
            "path": str(rel),
            "sha256_prefix": file_hash(src),
            "size_bytes": src.stat().st_size,
        })
        copied += 1

    manifest_path = snap_dir / "manifest.json"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print("Snapshot: " + snap_name)
    print("Location: " + str(snap_dir))
    print("Files archived: " + str(copied))
    return snap_dir


def do_file(filepath: str) -> Path | None:
    """Archive a single file into the latest or a new snapshot."""
    src = Path(filepath)
    if not src.is_absolute():
        src = PROJECT_ROOT / src
    if not src.is_file():
        print("File not found: " + str(src))
        sys.exit(1)

    rel = src.relative_to(PROJECT_ROOT)
    ts = timestamp_label()
    snap_dir = ARCHIVE_DIR / ("single_" + ts)
    dest = snap_dir / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)

    manifest = {
        "snapshot": "single_" + ts,
        "created": datetime.now().isoformat(),
        "label": "single-file archive of " + str(rel),
        "files": [{
            "path": str(rel),
            "sha256_prefix": file_hash(src),
            "size_bytes": src.stat().st_size,
        }],
    }
    with open(snap_dir / "manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)

    print("Archived: " + str(rel))
    print("Location: " + str(dest))
    return snap_dir


def do_list():
    """List all archived snapshots with summary info."""
    if not ARCHIVE_DIR.is_dir():
        print("No archive directory found.")
        return

    snaps = sorted(
        [d for d in ARCHIVE_DIR.iterdir() if d.is_dir()],
        key=lambda d: d.name,
    )
    if not snaps:
        print("No snapshots found.")
        return

    print("")
    print("Archived snapshots (" + str(ARCHIVE_DIR) + "):")
    print("")
    print("  Snapshot                              Files  Label")
    print("  " + "-" * 70)

    for snap in snaps:
        mf = snap / "manifest.json"
        if mf.is_file():
            with open(mf) as f:
                m = json.load(f)
            count = len(m.get("files", []))
            label = m.get("label", "")
        else:
            count = sum(1 for _ in snap.rglob("*") if _.is_file())
            label = ""
        print("  " + snap.name.ljust(40) + str(count).rjust(5) + "  " + label)

    print("")


def do_diff(snap1_name: str, snap2_name: str):
    """Compare two snapshots and show which files changed."""
    s1 = ARCHIVE_DIR / snap1_name
    s2 = ARCHIVE_DIR / snap2_name

    if not s1.is_dir():
        print("Snapshot not found: " + snap1_name)
        sys.exit(1)
    if not s2.is_dir():
        print("Snapshot not found: " + snap2_name)
        sys.exit(1)

    def load_manifest(snap_dir: Path) -> dict[str, str]:
        mf = snap_dir / "manifest.json"
        if not mf.is_file():
            return {}
        with open(mf) as f:
            m = json.load(f)
        return {entry["path"]: entry["sha256_prefix"] for entry in m.get("files", [])}

    m1 = load_manifest(s1)
    m2 = load_manifest(s2)
    all_paths = sorted(set(m1.keys()) | set(m2.keys()))

    added = []
    removed = []
    changed = []
    unchanged = []

    for p in all_paths:
        h1 = m1.get(p)
        h2 = m2.get(p)
        if h1 is None:
            added.append(p)
        elif h2 is None:
            removed.append(p)
        elif h1 != h2:
            changed.append(p)
        else:
            unchanged.append(p)

    print("")
    print("Diff: " + snap1_name + " -> " + snap2_name)
    print("")

    if added:
        print("  Added (" + str(len(added)) + "):")
        for p in added:
            print("    + " + p)
    if removed:
        print("  Removed (" + str(len(removed)) + "):")
        for p in removed:
            print("    - " + p)
    if changed:
        print("  Changed (" + str(len(changed)) + "):")
        for p in changed:
            print("    ~ " + p)
    if unchanged:
        print("  Unchanged (" + str(len(unchanged)) + "):")
        for p in unchanged:
            print("    = " + p)

    print("")
    print("Summary: " + str(len(added)) + " added, " + str(len(removed)) +
          " removed, " + str(len(changed)) + " changed, " +
          str(len(unchanged)) + " unchanged")


def do_restore(snap_name: str, filepath: str):
    """Restore a file from a snapshot to the current project."""
    snap_dir = ARCHIVE_DIR / snap_name
    if not snap_dir.is_dir():
        print("Snapshot not found: " + snap_name)
        sys.exit(1)

    src = snap_dir / filepath
    if not src.is_file():
        print("File not found in snapshot: " + filepath)
        print("Available files:")
        for f in sorted(snap_dir.rglob("*")):
            if f.is_file() and f.name != "manifest.json":
                print("  " + str(f.relative_to(snap_dir)))
        sys.exit(1)

    dest = PROJECT_ROOT / filepath
    dest.parent.mkdir(parents=True, exist_ok=True)

    # Auto-archive current version before restoring
    if dest.is_file():
        do_file(str(dest))
        print("(current version archived before restore)")

    shutil.copy2(src, dest)
    print("Restored: " + filepath + " from " + snap_name)


def archive_before_write(filepath: str) -> None:
    """Call from other scripts before overwriting a file.

    Usage in another script:
        from archive import archive_before_write
        archive_before_write("docs/BUSINESS_CASE.md")
    """
    src = Path(filepath)
    if not src.is_absolute():
        src = PROJECT_ROOT / src
    if src.is_file():
        do_file(str(src))


def main():
    parser = argparse.ArgumentParser(
        description="Archive manager for generated outputs. "
                    "(c) RSP Management Solutions LLC."
    )
    sub = parser.add_subparsers(dest="command")

    # snapshot
    sp = sub.add_parser("snapshot", help="Archive all current outputs")
    sp.add_argument("--label", "-l", help="Optional label for the snapshot")

    # file
    fp = sub.add_parser("file", help="Archive a single file")
    fp.add_argument("path", help="Path to the file to archive")

    # list
    sub.add_parser("list", help="List all archived snapshots")

    # diff
    dp = sub.add_parser("diff", help="Compare two snapshots")
    dp.add_argument("snap1", help="First snapshot name")
    dp.add_argument("snap2", help="Second snapshot name")

    # restore
    rp = sub.add_parser("restore", help="Restore a file from a snapshot")
    rp.add_argument("snap", help="Snapshot name")
    rp.add_argument("path", help="Relative file path to restore")

    args = parser.parse_args()

    if args.command == "snapshot":
        do_snapshot(args.label)
    elif args.command == "file":
        do_file(args.path)
    elif args.command == "list":
        do_list()
    elif args.command == "diff":
        do_diff(args.snap1, args.snap2)
    elif args.command == "restore":
        do_restore(args.snap, args.path)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
